
spring:
  cache:
    redis:
      time-to-live: 1800000 #??????(??)
      cache-null-values: true
  redis:
    host: 192.168.233.128
    port: 6379
    password: root
    database: 0

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db1?characterEncoding=utf8&useSSL=false
    username: root
    password: 1234



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/it/helloword/dao/*.xml
server:
  port: 8081
